'use client';

import React from 'react';
import { usePathname } from 'next/navigation';
import { useApiHealth } from '../../hooks/use-api-health';
import { Activity, RefreshCw } from 'lucide-react';

const TITLE_MAP: Record<string, { title: string; desc: string }> = {
  '/': { title: 'Dashboard', desc: 'Central AI control plane system health and active operations overview' },
  '/agents': { title: 'AI Agents', desc: 'Manage Fraud scoring, Payment recovery, and Growth incentive agents' },
  '/transactions': { title: 'Transactions', desc: 'Real-time transaction history and active fraud telemetry' },
  '/proposals': { title: 'Agent Proposals', desc: 'Review decision proposals generated by specialized agents' },
  '/decisions': { title: 'AgentShield Decisions', desc: 'Decisions and action overrides executed by AgentShield' },
  '/policies': { title: 'Merchant Policies', desc: 'Merchant-configured guardrail limits and business threshold values' },
  '/audit-logs': { title: 'Audit Logs', desc: 'Complete historical log trail of operational security actions' },
  '/demo': { title: 'Demo Scenarios', desc: 'Run sandbox demonstrations of the agent-shield lifecycle' },
};

export function Topbar() {
  const pathname = usePathname();
  const { status, checkHealth } = useApiHealth();
  
  const pageMeta = TITLE_MAP[pathname] || { title: 'AgentShield', desc: 'AI agent action safety plane' };

  return (
    <header className="hidden md:flex items-center justify-between px-8 py-4 border-b border-slate-900 bg-slate-950/40 sticky top-0 z-30 backdrop-blur-md">
      <div>
        <h2 className="text-lg font-bold text-white tracking-tight">{pageMeta.title}</h2>
        <p className="text-xs text-slate-500 font-medium">{pageMeta.desc}</p>
      </div>

      <div className="flex items-center gap-4">
        {/* Backend health indicator */}
        <div className="flex items-center gap-2.5 px-3 py-1.5 rounded-lg border border-slate-900 bg-slate-950">
          <Activity className="w-3.5 h-3.5 text-slate-500" />
          <span className="text-xs text-slate-400 font-medium select-none">API Backend:</span>
          
          {status === 'checking' && (
            <span className="flex items-center gap-1.5 text-xs text-amber-400 font-semibold">
              <span className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse" />
              Checking...
            </span>
          )}

          {status === 'connected' && (
            <span className="flex items-center gap-1.5 text-xs text-emerald-400 font-semibold">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
              Connected
            </span>
          )}

          {status === 'unavailable' && (
            <button
              onClick={checkHealth}
              className="flex items-center gap-1.5 text-xs text-rose-400 font-semibold hover:underline focus:outline-none cursor-pointer"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-rose-500" />
              Unavailable (Retry)
            </button>
          )}

          {status !== 'checking' && (
            <button
              onClick={checkHealth}
              className="p-0.5 rounded text-slate-500 hover:text-slate-300 hover:bg-slate-900/60 focus:outline-none cursor-pointer"
              aria-label="Refresh status"
            >
              <RefreshCw className="w-3 h-3" />
            </button>
          )}
        </div>
      </div>
    </header>
  );
}
