"""add policy embeddings table

Revision ID: cfc3bfa855a2
Revises: d173931aadd3
Create Date: 2026-08-23 21:13:32.950188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = 'cfc3bfa855a2'
down_revision: Union[str, Sequence[str], None] = 'd173931aadd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('document_content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['merchant_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_embeddings_merchant_id'), 'policy_embeddings', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_policy_embeddings_policy_id'), 'policy_embeddings', ['policy_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_embeddings_policy_id'), table_name='policy_embeddings')
    op.drop_index(op.f('ix_policy_embeddings_merchant_id'), table_name='policy_embeddings')
    op.drop_table('policy_embeddings')
    # ### end Alembic commands ###
